// src/pages/Dashboard/config/HodNavcards.js
import {
  Calendar,
  UserCheck,
  ClipboardList,
  Megaphone,
  NotebookPen,
  CalendarDays,
  Library,
  Microscope,
  Package,
  Wrench,
  Wallet,
  Banknote,
  CalendarClock,
  FileText,
  RotateCcw,
  ClipboardCheck,
  BookOpen
} from "lucide-react";

const hodNavCards = [
  {
  label: "My Courses",
  sublabel: "View Courses",
  route: "/my-courses",
  gradient: "from-blue-500 to-indigo-600",
  textColor: "text-blue-600 dark:text-blue-400",
  icon: BookOpen,
},
  {
    label: "Leave Approvals",
    sublabel: "Review & approve",
    route: "/hod-leave-dashboard",
    gradient: "from-teal-500 to-teal-600",
    textColor: "text-teal-600 dark:text-teal-400",
    icon: ClipboardCheck,
  },
  {
    label: "Schedule & Meetings",
    sublabel: "View Schedule",
    route: "/schedule",
    gradient: "from-rose-500 to-rose-600",
    textColor: "text-rose-600 dark:text-rose-400",
    icon: CalendarClock,
  },
  {
    label: "Calendar",
    sublabel: "View Calendar",
    route: "/calendar",
    gradient: "from-blue-500 to-indigo-600",
    textColor: "text-blue-600 dark:text-blue-400",
    icon: Calendar,
  },
  {
    label: "Attendance Management",
    sublabel: "Manage Attendance",
    route: "/attendance-management",
    gradient: "from-purple-500 to-purple-600",
    textColor: "text-purple-600 dark:text-purple-400",
    icon: UserCheck,
  },
  {
    label: "Session Planning",
    sublabel: "View Sessions",
    route: "/session-planning",
    gradient: "from-indigo-500 to-indigo-600",
    textColor: "text-indigo-600 dark:text-indigo-400",
    icon: ClipboardList,
  },
  {
    label: "Bulletins",
    sublabel: "View Bulletins",
    route: "/bulletins",
    gradient: "from-cyan-500 to-cyan-600",
    textColor: "text-cyan-600 dark:text-cyan-400",
    icon: Megaphone,
  },
  {
    label: "Exam Duties",
    sublabel: "View Duties",
    route: "/exam-duties",
    gradient: "from-lime-500 to-lime-600",
    textColor: "text-lime-600 dark:text-lime-400",
    icon: NotebookPen,
  },
  {
    label: "Leave Application",
    sublabel: "Apply for Leave",
    route: "/leave-applications",
    gradient: "from-orange-500 to-orange-600",
    textColor: "text-orange-600 dark:text-orange-400",
    icon: CalendarDays,
  },
  {
    label: "Library",
    sublabel: "Browse Books",
    route: "/library",
    gradient: "from-green-500 to-green-600",
    textColor: "text-green-600 dark:text-green-400",
    icon: Library,
  },
  {
    label: "Research & Publications",
    sublabel: "Browse Research",
    route: "/research-publications",
    gradient: "from-emerald-500 to-emerald-600",
    textColor: "text-emerald-600 dark:text-emerald-400",
    icon: Microscope,
  },
  {
    label: "Asset Requests",
    sublabel: "Request Assets",
    route: "/asset-requests",
    gradient: "from-teal-500 to-teal-600",
    textColor: "text-teal-600 dark:text-teal-400",
    icon: Package,
  },
  {
    label: "Maintenance Request",
    sublabel: "Request",
    route: "/maintenance",
    gradient: "from-yellow-500 to-yellow-600",
    textColor: "text-yellow-600 dark:text-yellow-400",
    icon: Wrench,
  },
  {
    label: "Finance Management",
    sublabel: "Manage Finances",
    route: "/finance-management",
    gradient: "from-amber-500 to-amber-600",
    textColor: "text-amber-600 dark:text-amber-400",
    icon: Wallet,
  },
  {
    label: "Payroll & Salary",
    sublabel: "View Breakdown",
    route: "/payroll",
    gradient: "from-blue-500 to-blue-600",
    textColor: "text-blue-600 dark:text-blue-400",
    icon: Banknote,
  },
  {
    label: "Registrar Office",
    sublabel: "Documents & Records",
    route: "/registrar",
    gradient: "from-violet-500 to-violet-600",
    textColor: "text-violet-600 dark:text-violet-400",
    icon: FileText,
  },
  {
  label: "Revaluation",
  sublabel: "Review Requests",
  route: "/revaluation",
  gradient: "from-violet-500 to-purple-600",
  textColor: "text-violet-600 dark:text-violet-400",
  icon: RotateCcw,
}

];

export default hodNavCards;