// src/pages/Dashboard/config/HrNavcards.js
import {
  Users,
  Calendar,
  CalendarDays,
  ClipboardCheck,
  Megaphone,
  Banknote,
  Wallet,
  Package,
  Wrench,
  FileText,
  UserPlus,
  ShieldCheck,
  TrendingUp,
  CalendarClock,
  Library,
  Building2,
} from "lucide-react";

const hrNavCards = [
  {
    label: "Leave Approvals",
    sublabel: "Review & approve",
    route: "/hod-leave-dashboard",
    gradient: "from-rose-500 to-rose-600",
    textColor: "text-rose-600 dark:text-rose-400",
    icon: ClipboardCheck,
  },
 
  {
    label: "Payroll & Salary",
    sublabel: "Manage Payroll",
    route: "/payroll",
    gradient: "from-emerald-500 to-emerald-600",
    textColor: "text-emerald-600 dark:text-emerald-400",
    icon: Banknote,
  },
  {
    label: "Attendance Management",
    sublabel: "Track Attendance",
    route: "/attendance-management",
    gradient: "from-purple-500 to-purple-600",
    textColor: "text-purple-600 dark:text-purple-400",
    icon: ShieldCheck,
  },
  {
    label: "Schedule & Meetings",
    sublabel: "View Schedule",
    route: "/schedule",
    gradient: "from-cyan-500 to-cyan-600",
    textColor: "text-cyan-600 dark:text-cyan-400",
    icon: CalendarClock,
  },
  {
    label: "Calendar",
    sublabel: "View Calendar",
    route: "/calendar",
    gradient: "from-sky-500 to-blue-600",
    textColor: "text-sky-600 dark:text-sky-400",
    icon: Calendar,
  },
  {
    label: "Leave Application",
    sublabel: "Apply for Leave",
    route: "/leave-applications",
    gradient: "from-orange-500 to-orange-600",
    textColor: "text-orange-600 dark:text-orange-400",
    icon: CalendarDays,
  },
  {
    label: "Finance Management",
    sublabel: "Manage Finances",
    route: "/finance-management",
    gradient: "from-amber-500 to-amber-600",
    textColor: "text-amber-600 dark:text-amber-400",
    icon: Wallet,
  },
  {
    label: "Performance Reviews",
    sublabel: "Evaluate Staff",
    route: "/performance-reviews",
    gradient: "from-lime-500 to-lime-600",
    textColor: "text-lime-600 dark:text-lime-400",
    icon: TrendingUp,
  },
  {
    label: "Bulletins",
    sublabel: "View Bulletins",
    route: "/bulletins",
    gradient: "from-teal-500 to-teal-600",
    textColor: "text-teal-600 dark:text-teal-400",
    icon: Megaphone,
  },
  {
    label: "Asset Requests",
    sublabel: "Request Assets",
    route: "/asset-requests",
    gradient: "from-indigo-500 to-indigo-600",
    textColor: "text-indigo-600 dark:text-indigo-400",
    icon: Package,
  },
  {
    label: "Maintenance Request",
    sublabel: "Request",
    route: "/maintenance",
    gradient: "from-yellow-500 to-yellow-600",
    textColor: "text-yellow-600 dark:text-yellow-400",
    icon: Wrench,
  },
  {
    label: "Registrar Office",
    sublabel: "Documents & Records",
    route: "/registrar",
    gradient: "from-fuchsia-500 to-fuchsia-600",
    textColor: "text-fuchsia-600 dark:text-fuchsia-400",
    icon: FileText,
  },
  {
    label: "Library",
    sublabel: "Browse Books",
    route: "/library",
    gradient: "from-green-500 to-green-600",
    textColor: "text-green-600 dark:text-green-400",
    icon: Library,
  },
  {
    label: "Department Overview",
    sublabel: "View Departments",
    route: "/department-overview",
    gradient: "from-pink-500 to-rose-600",
    textColor: "text-pink-600 dark:text-pink-400",
    icon: Building2,
  },
];

export default hrNavCards;