// config/navCards.js
import {
  TestTubes,
  Building2,
  Calendar as CalendarIcon,
  GraduationCap,
  BookMarked,
  AlertCircle,
  Home,
  Briefcase,
  FileText,
  ClipboardList,
  Users,
  Book,
  IndianRupee,
  CheckCircle2,
  RotateCcw
} from "lucide-react";

const navCards = [
  {
    label: "My Courses",
    sublabel: "View Courses",
    route: "/my-courses",
    gradient: "from-blue-500 to-indigo-600",
    textColor: "text-blue-600 dark:text-blue-400",
    icon: BookMarked,
  },
  {
    label: "Hostel",
    sublabel: "Manage Hostel",
    route: "/hostel",
    gradient: "from-orange-500 to-amber-600",
    textColor: "text-orange-600 dark:text-orange-400",
    icon: Home,
  },
  {
    label: "Placement Cell",
    sublabel: "Jobs & Internships",
    route: "/placement",
    gradient: "from-emerald-500 to-teal-600",
    textColor: "text-emerald-600 dark:text-emerald-400",
    icon: Briefcase,
  },
  {
    label: "Registrar Office",
    sublabel: "Documents & Records",
    route: "/registrar",
    gradient: "from-purple-500 to-violet-600",
    textColor: "text-purple-600 dark:text-purple-400",
    icon: FileText,
  },
  {
    label: "Examinations",
    sublabel: "Schedule & Results",
    route: "/examinations",
    gradient: "from-rose-500 to-pink-600",
    textColor: "text-rose-600 dark:text-rose-400",
    icon: ClipboardList,
  },
  {
    label: "Mentor",
    sublabel: "My Mentor",
    route: "/mentor",
    gradient: "from-cyan-500 to-sky-600",
    textColor: "text-cyan-600 dark:text-cyan-400",
    icon: Users,
  },
  {
    label: "Library",
    sublabel: "Library Resources",
    route: "/library",
    gradient: "from-emerald-500 to-teal-600",
    textColor: "text-emerald-600 dark:text-emerald-400",
    icon: Book,
  },
  {
    label: "Finance",
    sublabel: "Fees & Payments",
    route: "/finance",
    gradient: "from-green-500 to-emerald-600",
    textColor: "text-green-600 dark:text-green-400",
    icon: IndianRupee,
  },
  {
    label: "Student Attendance",
    sublabel: "View Attendance",
    route: "/student-attendance",
    gradient: "from-teal-500 to-cyan-600",
    textColor: "text-teal-600 dark:text-teal-400",
    icon: CheckCircle2,
  },
  {
    label: "Calendar",
    sublabel: "Schedule & Events",
    route: "/calendar",
    gradient: "from-indigo-500 to-purple-600",
    textColor: "text-indigo-600 dark:text-indigo-400",
    icon: CalendarIcon,
  },
  {
    label: "Announcements",
    sublabel: "View Announcements",
    route: "/announcements",
    gradient: "from-red-500 to-rose-600",
    textColor: "text-red-600 dark:text-red-400",
    icon: AlertCircle,
  },
  {
    label: "Research",
    sublabel: "Publications & Projects",
    route: "/student-research",
    gradient: "from-purple-500 to-violet-600",
    textColor: "text-violet-600 dark:text-violet-400",
    icon: TestTubes,
  },
  {
    label: "Schedule & Planner",
    sublabel: "Today & Weekly Plan",
    route: "/student-schedule",
    gradient: "from-blue-500 to-indigo-600",
    textColor: "text-blue-600 dark:text-blue-400",
    icon: CalendarIcon,
  },
  {
  label: "Revaluation",
  sublabel: "Apply & Track",
  route: "/revaluation",
  gradient: "from-violet-500 to-purple-600",
  textColor: "text-violet-600 dark:text-violet-400",
  icon: RotateCcw,
},
];

export default navCards;