FROM nginx:1.21

# Install required packages
RUN apt-get update && apt-get install -y cron logrotate

# Remove the default nginx configuration
RUN rm -f /etc/nginx/conf.d/default.conf

COPY ./default_dev.template /etc/nginx/conf.d/default_dev.template
COPY ./nginx_dev.conf /etc/nginx/nginx.conf
COPY ./entrypoint_dev.sh /usr/local/bin/entrypoint_dev.sh
COPY ./logrotate.conf /etc/logrotate.d/nginx

RUN chmod +x /usr/local/bin/entrypoint_dev.sh

EXPOSE 80
ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint_dev.sh"]